name: dart_avro
description: Pure dart implementation of apache avro encoding and decoding
version: 0.0.3
homepage: https://github.com/krikristoophe/dart_avro

environment:
  sdk: ^3.5.0

dev_dependencies:
  test: ^1.25.7
  very_good_analysis: ^6.0.0
