name: dart_avro
description: "Flutter wrapper for avro"
# version: 0.0.1
homepage: https://github.com/krikristoophe/dart_avro

environment:
  sdk: ^3.5.0

dev_dependencies:
  test: ^1.25.7
  very_good_analysis: ^6.0.0
